### 1. Write a Python Program to Add Two Matrices?

In [2]:
import numpy as np

mat1 = np.array([[1,2,3],[2,3,4]])  # shape 2,3
mat2 = np.array([[78,54,3],[67,45,7]])

print(mat1 + mat2)

[[79 56  6]
 [69 48 11]]


### 2. Write a Python Program to Multiply Two Matrices?

In [6]:
import numpy as np

mat1 = np.array([[1,2,3],[2,3,4]])  # shape 2,3
mat2 = np.array([[78,54,3],[67,45,7],[23,1,4]])

print(mat1@mat2)

[[281 147  29]
 [449 247  43]]


### 3. Write a Python Program to Transpose a Matrix?

In [7]:
import numpy as np

mat1 = np.array([[1,2,3],[2,3,4]]) # shape of matrix is 2 , 3

# shape changes to 3 , 2
mat1.T

array([[1, 2],
       [2, 3],
       [3, 4]])

### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [10]:
def sort_words(lis):
    
    if type(lis) == list:
        
        lis.sort()
        
        return lis
    
    else :
        
        return 'Please give the list data type data!'

In [11]:
sort_words(['pasta','pizza','apple','banana','cakes'])

['apple', 'banana', 'cakes', 'pasta', 'pizza']

### 5. Write a Python Program to Remove Punctuation From a String?

In [12]:
def filter_string(string):
    
    if type(string) == str:
        
        string1 = ''
        
        for i in string:
            
            if (ord(i)>=65 and ord(i)<=90) or (ord(i)>=97 and ord(i)<=122) or (ord(i)>=48 and ord(i)<=55):
                
                string1 += i
                
        return string1
    
    else:
        
        return "Please give string data type data!"

In [13]:
filter_string('ar$%y*a(n)')

'aryan'